version: "3"

services:
  python:
    build: python/.
    volumes:
      - ./python/:/python 
    ports:
      - "5000:8000"
    environment:
      VIRTUAL_HOST: python.localhost
  auth:
    build: golang/.
    volumes:
      - ./golang/:/golang   
    ports:
      - "3000:8000"
    environment:
      VIRTUAL_HOST: golang.localhost
  social:
    build: rust/.
    volumes:
      - ./rust/:/rust    
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: rust.localhost
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d/:/etc/nginx/vhost.d
